{
 "title": "Custom WebSocket Statistics",
 "tags": [
  "websocket",
  "shoppy"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(websocket_sessions, application)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total WS Sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "websocket_sessions{application=\"$application\"}"
    }
   ]
  },
  {
   "title": "WS Request Count (per destination)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum by (destination) (irate(websocket_request_seconds_count{application=\"$application\"}[$__rate_interval]))",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "WS Avg Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(websocket_request_seconds_sum{application=\"$application\"}[$__rate_interval]) / rate(websocket_request_seconds_count{application=\"$application\"}[$__rate_interval])",
     "legendFormat": "{{destination}}"
    }
   ]
  }
 ]
}