### 전체 상품 조회 (페이징 없음)
GET http://localhost:8080/api/products
Content-Type: application/json

### 전체 상품 조회 (페이징 적용)
GET http://localhost:8080/api/products?page=0&size=10
Content-Type: application/json

### 전체 상품 조회 (2페이지)
GET http://localhost:8080/api/products?page=1&size=10
Content-Type: application/json

### 상품 검색 (페이징 없음)
GET http://localhost:8080/api/products/search?keyword=우유
Content-Type: application/json

### 상품 검색 (페이징 적용)
GET http://localhost:8080/api/products/search?keyword=우유&page=0&size=5
Content-Type: application/json
