spring:
  application:
    name: shoppy
  profiles:
    active: local

server:
  servlet:
    context-path: /api
# kjs start
google:
  cloud:
    vision:
      credentials-path: ${GOOGLE_APPLICATION_CREDENTIALS:}
# kjs end
